### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [GoergPflug/AttinyStreamGfxApi#3]
Hello!

I found your project from https://hackaday.com/2022/04/12/mindblowing-graphics-from-an-attiny85/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by GoergPflug** [comment]
it is free under the bsd llicense, right now the text is only in the source, i will add it to a more prominent place

**Comment by vazhnov** [comment]
BSD license — cool!
@GoergPflug , thank you!

**Comment by vazhnov** [comment]
@GoergPflug, I can help to add SPDX identifier into all source files, but I don't know which one to choose in https://spdx.org/licenses/ , I see ~19 different BSD licenses…
