### ISSUE TITLE
ATMEGA328P

### ISSUE THREAD

**Issue by ricardojlrufino** [GoergPflug/AttinyStreamGfxApi#4]
would this work on ATMEGA328P?

**Comment by GoergPflug** [comment]
the library should run on any arduino, but it will probably not be any
faster than on the attiny, because it is using wire-i2c, and wire is a bit
slow.


Am Mi., 13. Apr. 2022 um 03:47 Uhr schrieb Ricardo JL Rufino <
***@***.***>:
