### ISSUE TITLE
Missing return type in tiny_multi_os.h

### ISSUE THREAD

**Issue by Austinrocket** [GoergPflug/AttinyStreamGfxApi#6]
ISO C++ forbids declaration of 'GfxApiPosition' with no type [-fpermissive] static inline GfxApiPosition(unsigned char x, unsigned char y)

Line 37: static inline GfxApiPosition(unsigned char x, unsigned char y)
should be
**unsigned char** static inline GfxApiPosition(unsigned char x, unsigned char y)

Love the library! Working on getting something working with Digispark+ssd1306

**Comment by GoergPflug** [comment]
oooops, thanks, fixed it.

if you do something with it drop me a line, i am interested in what other
people do with it.


Am Fr., 29. Apr. 2022 um 07:39 Uhr schrieb Austinrocket <
***@***.***>:
