### ISSUE TITLE
Need to set page address settings explicitly

### ISSUE THREAD

**Issue by SR151221** [GoergPflug/AttinyStreamGfxApi#7]
Dear Görg,
thank you very much for your fine library!

I faced a problem with it: the display started from page 7, then continued at page 0 and so forth through page 6.
See attached screenshot - the top part of the arc is at the bottom of the screen. 
[ssd1306 page error](https://user-images.githubusercontent.com/122114408/211064903-a3953af6-cde8-4574-a671-10ff1407d81a.jpg)

This happened both with ATtiny85 and Arduino Uno (ATmega328), with two similar display items, with any test demo you provided.
Besides, the pixels which were expected to be in column 127 were actually displayed in column 0. And there also were several parasyte pixels at the bottom of column 0.

Somewhere I read that it is recommended to explicitly set SSD1306 parameters even if they repeat defaults, otherwise the chip might behave erratically.
So, I added page address settings **0x22, 0x00, 0x07** to function **os_gfx_start_display_transfer()**, right after 0x21, 0x00, 0x7F sequence, and it completely fixed those issues.

Hope this will be useful.

Thank you!

**Comment by GoergPflug** [comment]
thanks a lot!

I added a bugfix, (see the tinymultios in the main directory of the repo...) i hope it works i have never encountered this issue, there seem to be different versions of the chip with subtile differences. if you look at the datasheet it seems plausible that doing this will at least not hurt anything.

:)
Have a nice Sunday... Görg
